[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "Artificial Intelligence and Creativity: Can Machines Be Creative? Exploring the Intersection of Art and Science"
